markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - admonition
  - pymdownx.arithmatex
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.snippets:
      base_path: ["docs/snippets"]
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.css

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - toc.integrate

site_name: Krux - Open-source signing device firmware for Bitcoin
site_description: Krux is open-source firmware that enables anyone to build their own Bitcoin signing device via off-the-shelf parts.
site_url: https://selfcustody.github.io/krux/
repo_url: https://github.com/selfcustody/krux
edit_uri: edit/main/docs
docs_dir: docs
site_dir: public
extra:
  latest_krux: krux-v25.11.beta2
  latest_installer: v0.0.21
  latest_installer_rpm: krux_installer-0.0.21-1.x86_64.rpm
  latest_installer_deb: krux_installer_0.0.21_amd64.deb
  latest_installer_win: krux_installer_v0.0.21_Setup.exe
  latest_installer_mac_arm: krux_installer_0.0.21_arm64.dmg
  latest_installer_mac_intel: krux-installer_0.0.20_x86_64.dmg
  latest_installer_sha: krux-installer.SHA256.txt
  latest_installer_sig: krux-installer.SHA256.txt.sig
  latest_installer_key: B4281DDDFBBD207BFA4113138974C90299326322
  latest_installer_keyserver: hkps://keys.openpgp.org
  social:
    - icon: fontawesome/solid/bullhorn
      link: https://bitcointalk.org/index.php?topic=5489022.0
      name: Send a message to the Bitcoin Forum
    - icon: fontawesome/brands/telegram
      link: https://t.me/KruxDIY
      name: Join our community-led Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/selfcustodykrux
      name: Follow us on X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/selfcustody/krux
      name: Our code on Github
  generator: false
copyright: 
  Powered by <a href="https://embit.rocks/">embit</a>, the Bitcoin library for Python 3 and Micropython

nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: getting-started/index.md
    - Installing:
      - Installing: getting-started/installing/index.md
      - From GUI application:
<<<<<<< HEAD
        - From GUI application: getting-started/installing/from-gui/index.en.md
        - Verify: getting-started/installing/from-gui/verify-download.en.md
        - Windows: getting-started/installing/from-gui/windows.en.md
        - MacOS: getting-started/installing/from-gui/macos.en.md
        - Debian-like: getting-started/installing/from-gui/debian-like.en.md
        - Fedora-like: getting-started/installing/from-gui/fedora-like.en.md
        - Other linux distro: getting-started/installing/from-gui/other-linux-distro.en.md
        - Usage: getting-started/installing/from-gui/usage.en.md
      - From pre-built official release: getting-started/installing/from-pre-built-release.en.md
      - From pre-built test release: getting-started/installing/from-test-release.en.md
      - From source: getting-started/installing/from-source.en.md
=======
        - From GUI application: getting-started/installing/from-gui/index.md
        - Windows: getting-started/installing/from-gui/windows.md
        - MacOS Intel: getting-started/installing/from-gui/macos-intel.md
        - MacOS ARM64: getting-started/installing/from-gui/macos-arm64.md
        - Debian-like: getting-started/installing/from-gui/debian-like.md
        - Fedora-like: getting-started/installing/from-gui/fedora-like.md
        - Other linux distro: getting-started/installing/from-gui/other-linux-distro.md
        - Usage: getting-started/installing/from-gui/usage.md
      - From pre-built official release: getting-started/installing/from-pre-built-release.md
      - From pre-built test release: getting-started/installing/from-test-release.md
      - From source: getting-started/installing/from-source.md
>>>>>>> 748f0fab (fix menu for translations)
    - Basic Usage:
      - Basic Usage: getting-started/usage/index.md
      - Generating a Mnemonic: getting-started/usage/generating-a-mnemonic.md
      - Loading a Mnemonic: getting-started/usage/loading-a-mnemonic.md
      - Navigating the Main Menu: getting-started/usage/navigating-the-main-menu.md
      - Setting a Coordinator and Signing: getting-started/usage/setting-a-coordinator-and-signing.md
  - Exploring Features:
    - Features:
      - Encryption:
        - Encryption Introduction: getting-started/features/encryption/encryption.md
        - KEF Specifications: getting-started/features/encryption/kef-specifications.md
      - Printing:
        - Printing: getting-started/features/printing/printing.md
        - CNC Engraving: getting-started/features/printing/cnc.md
      - SD Card Updates: getting-started/features/sd-card-update.md
      - Tools: getting-started/features/tools.md
      - Transcribing QR Codes: getting-started/features/QR-transcript-tools.md
      - Tiny Seed and other metal plates: getting-started/features/tinyseed.md
      - Empirical Entropy Measurement: getting-started/features/entropy.md
      - Tamper Detection: getting-started/features/tamper-detection.md
      - Mnemonic XOR: getting-started/features/mnemonic-xor.md
    - Interface:
      - Navigation overview: getting-started/navigation.md
      - Settings: getting-started/settings.md
      - Templates: getting-started/templates/templates.md
  - Video Tutorials: video-tutorials.md
  - Devices and Parts List: parts.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
  - Support the Project: support.md

plugins:
 - search
 - macros
 - i18n:
    docs_structure: suffix
    default_language: en
    languages:
      - locale: en
        default: true
        name: English
        build: true
      - locale: es
        name: Español
        build: true
        site_name: Krux - Programa de código abierto de equipos de firma para Bitcoin 
        nav_translations:
          Home: Inicio
          Getting Started: Primeros Pasos
          Devices and Parts List: Dispositivos y Lista de Piezas
          FAQ: Preguntas Frecuentes
          Support the Project: Apoyar el Proyecto
          About: Acerca de
          Installing: Instalando 
          Generating a Mnemonic: Generar una Mnemónica
          Loading a Mnemonic: Cargar una Mnemónica
          Navigating the Main Menu: Navegar el Menú Principal
          Using a Single-sig Wallet: Usando una Billetera de Firma Única
          Using a Multisig Wallet: Usando una Billetera Multifirma
          Printing: Imprimiendo
          Settings: Ajustes
