markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - js/tabsync.js

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    primary: white
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - toc.integrate

site_name: Krux - Open-source signing device firmware for Bitcoin
site_description: Krux is open-source firmware that enables anyone to build their own Bitcoin signing device via off-the-shelf parts.
site_url: https://selfcustody.github.io/krux/
repo_url: https://github.com/selfcustody/krux
edit_uri: edit/main/docs
docs_dir: docs
site_dir: public
extra:
  social:
    - icon: material/chat
      link: https://matrix.to/#/#krux:matrix.org
      name: Join our Matrix server
    - icon: fontawesome/brands/telegram
      link: https://t.me/SC_Krux
      name: Join our community-led Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/selfcustody/krux
  generator: true
copyright: 
  Powered by <a href="https://embit.rocks/">embit</a>, the Bitcoin library for Python 3 and Micropython

nav:
  - Home: index.en.md
  - Getting Started:
    - About: getting-started/index.en.md
    - Installing: getting-started/installing.en.md
    - Generating a Mnemonic: getting-started/generating-a-mnemonic.en.md
    - Loading a Mnemonic: getting-started/loading-a-mnemonic.en.md
    - Navigating the Main Menu: getting-started/navigating-the-main-menu.en.md
    - Using a Single-sig Wallet: getting-started/using-a-single-sig-wallet.en.md
    - Using a Multisig Wallet: getting-started/using-a-multisig-wallet.en.md
    - Printing: getting-started/printing.en.md
    - Settings: getting-started/settings.en.md
  - Part List: parts.en.md
  - FAQ: faq.en.md
  - Support the Project: support.en.md

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
